=begin
#Merchandice Data Scraping API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MerchandiceScraperSdk::RunsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RunsApi' do
  before do
    # run before each test
    @api_instance = MerchandiceScraperSdk::RunsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RunsApi' do
    it 'should create an instance of RunsApi' do
      expect(@api_instance).to be_instance_of(MerchandiceScraperSdk::RunsApi)
    end
  end

  # unit tests for api_scrapers_scraper_id_runs_get
  # Retrieves collection
  # @param scraper_id The ID of the scraper the run is associated with.
  # @param [Hash] opts the optional parameters
  # @return [Array<ScraperRunResponse>]
  describe 'api_scrapers_scraper_id_runs_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_scrapers_scraper_id_runs_id_get
  # Retrieves member
  # @param scraper_id The ID of the scraper the run is associated with.
  # @param id The ID of the scraper run to retrieve.
  # @param [Hash] opts the optional parameters
  # @return [ScraperRunResponse]
  describe 'api_scrapers_scraper_id_runs_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_scrapers_scraper_id_runs_post
  # Creates new run
  # @param scraper_id The ID of the scraper the run is associated with.
  # @param [Hash] opts the optional parameters
  # @option opts [ScraperRun] :scraper_run The representation of the scraper run to create.
  # @return [nil]
  describe 'api_scrapers_scraper_id_runs_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
