=begin
#Merchandice Data Scraping API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MerchandiceScraperSdk::URLsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'URLsApi' do
  before do
    # run before each test
    @api_instance = MerchandiceScraperSdk::URLsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of URLsApi' do
    it 'should create an instance of URLsApi' do
      expect(@api_instance).to be_instance_of(MerchandiceScraperSdk::URLsApi)
    end
  end

  # unit tests for api_scrapers_scraper_id_runs_run_id_urls_get
  # Retrieves collection
  # @param scraper_id The ID of the URL is associated with.
  # @param run_id The ID of the scraper run the URL is associated with.
  # @param [Hash] opts the optional parameters
  # @return [Array<ScraperRunURLResponse>]
  describe 'api_scrapers_scraper_id_runs_run_id_urls_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_scrapers_scraper_id_runs_run_id_urls_id_get
  # Retrieves member
  # @param scraper_id The ID of the scraper the URL is associated with.
  # @param run_id The ID of the scraper run the URL is associated with.
  # @param id The ID of the URL to retrieve.
  # @param [Hash] opts the optional parameters
  # @return [ScraperRunURLResponse]
  describe 'api_scrapers_scraper_id_runs_run_id_urls_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_scrapers_scraper_id_runs_run_id_urls_post
  # Creates new run URL
  # @param scraper_id The ID of the URL is associated with.
  # @param run_id The ID of the scraper run the URL is associated with.
  # @param [Hash] opts the optional parameters
  # @option opts [ScraperRunURL] :scraper_run_url 
  # @return [nil]
  describe 'api_scrapers_scraper_id_runs_run_id_urls_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
