=begin
#Merchandice Data Scraping API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MerchandiceScraperSdk::ScraperWebhookActionRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MerchandiceScraperSdk::ScraperWebhookActionRequest do
  let(:instance) { MerchandiceScraperSdk::ScraperWebhookActionRequest.new }

  describe 'test an instance of ScraperWebhookActionRequest' do
    it 'should create an instance of ScraperWebhookActionRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MerchandiceScraperSdk::ScraperWebhookActionRequest)
    end
  end

  describe 'test attribute "headers"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "body"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["options", "get", "head", "post", "put", "delete", "trace", "connect", "propfind", "proppatch", "mkcol", "copy", "move", "lock", "unlock", "version_control", "report", "checkout", "checkin", "uncheckout", "mkworkspace", "update", "label", "merge", "baseline_control", "mkactivity", "orderpatch", "acl", "search", "mkcalendar", "patch"])
      # validator.allowable_values.each do |value|
      #   expect { instance.method = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "for_each"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
