=begin
#Merchandice Data Scraping API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MerchandiceScraperSdk::ScraperRunURL
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MerchandiceScraperSdk::ScraperRunURL do
  let(:instance) { MerchandiceScraperSdk::ScraperRunURL.new }

  describe 'test an instance of ScraperRunURL' do
    it 'should create an instance of ScraperRunURL' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MerchandiceScraperSdk::ScraperRunURL)
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "target_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
